-- Arquivo legado do projeto original.
-- Contém comandos SQL usados como referência durante a refatoração.
-- Será separado futuramente em schema.sql, seed.sql e queries.sql.


DROP DATABASE IF EXISTS DBPROJETOINTEGRADOR;
CREATE DATABASE DBPROJETOINTEGRADOR;
USE DBPROJETOINTEGRADOR;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(50) NOT NULL
    , EMAIL VARCHAR(100) NOT NULL
    , SENHA VARCHAR(200) NOT NULL
    , PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE CATEGORIA(
  IDCATEGORIA INT NOT NULL AUTO_INCREMENT
  , NOME VARCHAR(100) NOT NULL
  , PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE PRODUTO(
  IDPRODUTO INT NOT NULL AUTO_INCREMENT
  , IDCATEGORIA INT NOT NULL
  , NOME VARCHAR(100) NOT NULL
  , DESCRICAO VARCHAR(300) NULL
  , CONTROLE_VALIDADE CHAR(1) NOT NULL
  , ESTOQUE_MINIMO INT NULL
  , PRIMARY KEY (IDPRODUTO)
  , FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA)
);

CREATE TABLE FORNECEDOR(
  IDFORNECEDOR INT NOT NULL AUTO_INCREMENT
  , NOME VARCHAR(100) NOT NULL
  , TELEFONE VARCHAR(15) NULL
  , EMAIL VARCHAR(100) NULL
  , PRIMARY KEY (IDFORNECEDOR)
);

CREATE TABLE LOTE (
  IDLOTE INT NOT NULL AUTO_INCREMENT
  , IDPRODUTO INT NOT NULL
  , IDFORNECEDOR INT NOT NULL
  , DATA_CADASTRO DATE NOT NULL
  , DATA_VALIDADE DATE NOT NULL
  , NUMERO VARCHAR(45) NOT NULL
  , QUANTIDADE INT NULL
  , PRIMARY KEY (IDLOTE)
  , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
  , FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR (IDFORNECEDOR)
);

CREATE TABLE MOVIMENTACAO (
  IDMOVIMENTACAO INT NOT NULL AUTO_INCREMENT
  , IDLOTE INT NOT NULL
  , IDUSUARIO INT NOT NULL
  , DATA_MOVIMENTOCAO DATE NOT NULL
  , TIPO VARCHAR(10) NOT NULL
  , QUANTIDADE INT NOT NULL
  , VALOR_UNITARIO DECIMAL(8,2) NOT NULL
  , MOTIVO VARCHAR(50) NOT NULL
  , PRIMARY KEY (IDMOVIMENTACAO)
  , FOREIGN KEY (IDLOTE) REFERENCES LOTE(IDLOTE)
  , FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

-- CONSULTA PARA CALCULAR ESTOQUE A PARTIR DA MOVINTACAO
CREATE VIEW VW_ESTOQUE AS 
SELECT 
	IDPRODUTO
	, ESTOQUE_MINIMO
    , IDLOTE
	, ESTOQUE
    , CASE WHEN ESTOQUE < ESTOQUE_MINIMO AND ESTOQUE_MINIMO > 0 THEN 'S' ELSE 'N' END ALERTA_ESTOQUE
FROM (
	SELECT 
		PRODUTO.IDPRODUTO
		, IFNULL(PRODUTO.ESTOQUE_MINIMO, 0) AS ESTOQUE_MINIMO
		, IFNULL(SUM(CASE WHEN MOVIMENTACAO.TIPO = 'SAIDA' THEN -1 ELSE 1 END * MOVIMENTACAO.QUANTIDADE), 0) AS ESTOQUE
        , (SELECT SUB.IDLOTE FROM LOTE SUB WHERE SUB.IDPRODUTO = PRODUTO.IDPRODUTO ORDER BY SUB.IDPRODUTO, LOTE.DATA_VALIDADE LIMIT 1) AS IDLOTE
	FROM
		PRODUTO
		LEFT JOIN LOTE ON
		LOTE.IDPRODUTO = PRODUTO.IDPRODUTO
		LEFT JOIN MOVIMENTACAO ON
		MOVIMENTACAO.IDLOTE = LOTE.IDLOTE
	GROUP BY
		PRODUTO.IDPRODUTO
        , IDLOTE
) AS BASE;



SELECT * FROM USUARIO;
SELECT * FROM CATEGORIA;
SELECT * FROM FORNECEDOR;
SELECT * FROM PRODUTO;
SELECT * FROM LOTE;
SELECT * FROM MOVIMENTACAO;
SELECT * FROM VW_ESTOQUE;

INSERT INTO categoria (NOME) VALUES ('Teste');


