CREATE TABLE IF NOT EXISTS USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(50) NOT NULL
    , EMAIL VARCHAR(100) NOT NULL
    , SENHA VARCHAR(200) NOT NULL
    , PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
  IDCATEGORIA INT NOT NULL AUTO_INCREMENT
  , NOME VARCHAR(100) NOT NULL
  , PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
  IDPRODUTO INT NOT NULL AUTO_INCREMENT
  , IDCATEGORIA INT NOT NULL
  , NOME VARCHAR(100) NOT NULL
  , DESCRICAO VARCHAR(300) NULL
  , CONTROLE_VALIDADE CHAR(1) NOT NULL
  , ESTOQUE_MINIMO INT NULL
  , PRIMARY KEY (IDPRODUTO)
  , FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
  IDFORNECEDOR INT NOT NULL AUTO_INCREMENT
  , NOME VARCHAR(100) NOT NULL
  , TELEFONE VARCHAR(15) NULL
  , EMAIL VARCHAR(100) NULL
  , PRIMARY KEY (IDFORNECEDOR)
);

CREATE TABLE IF NOT EXISTS LOTE (
  IDLOTE INT NOT NULL AUTO_INCREMENT
  , IDPRODUTO INT NOT NULL
  , IDFORNECEDOR INT NOT NULL
  , DATA_CADASTRO DATE NOT NULL
  , DATA_VALIDADE DATE NOT NULL
  , NUMERO VARCHAR(45) NOT NULL
  , QUANTIDADE INT NULL
  , PRIMARY KEY (IDLOTE)
  , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
  , FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR (IDFORNECEDOR)
);

CREATE TABLE IF NOT EXISTS MOVIMENTACAO (
  IDMOVIMENTACAO INT NOT NULL AUTO_INCREMENT
  , IDLOTE INT NOT NULL
  , IDUSUARIO INT NOT NULL
  , DATA_MOVIMENTOCAO DATE NOT NULL
  , TIPO VARCHAR(10) NOT NULL
  , QUANTIDADE INT NOT NULL
  , VALOR_UNITARIO DECIMAL(8,2) NOT NULL
  , MOTIVO VARCHAR(50) NOT NULL
  , PRIMARY KEY (IDMOVIMENTACAO)
  , FOREIGN KEY (IDLOTE) REFERENCES LOTE(IDLOTE)
  , FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);